### ISSUE TITLE
Signed Addition

### ISSUE THREAD

**Issue by FierceExplorer** [CalrethilOfMirkwood/flask_portfolio#25]
Integer Numbers.  Subtraction: 8th bit is a Sign, max number is +127 and min is -128, overflow now produces a negative number.

**Comment by CalrethilOfMirkwood** [comment]
Commit: https://github.com/CalrethilOfMirkwood/flask_portfolio/commit/5477f3f4d268088cd8f6253fb164fbf32257bc28

I have gotten the base structure of [signedaddition.html](https://github.com/CalrethilOfMirkwood/flask_portfolio/blob/main/templates/signedaddition.html) set up: there are two rows of lightbulbs and each has its own set of functions that are identical in all except name so that I can calculate their values seperately.

I still need to add a third row to show the sum of the two numbers.  I plan to add the two calculated numbers in decimal together and convert that result to binary and display it with the lightbulbs.  I also need to decide what happens if the sum is greater than 127 or less than -128.
